// Generated by scripts/generate-abi.mjs. Do not edit manually.

export const ABI = [
  {
    "type": "error",
    "name": "AppealWindowNotOpen",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadEthValue",
    "inputs": [
      {
        "name": "sent",
        "type": "uint256"
      },
      {
        "name": "expectedMin",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "CannotRemoveDefaultImplementation",
    "inputs": [
      {
        "name": "implementation",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ClaimFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CreatorCannotBeRemoved",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CreatorCannotLeave",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DisputeAlreadyExists",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DisputeNotFound",
    "inputs": [
      {
        "name": "disputeId",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC20InsufficientAllowance",
    "inputs": [
      {
        "name": "spender",
        "type": "address"
      },
      {
        "name": "allowance",
        "type": "uint256"
      },
      {
        "name": "needed",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC20InsufficientBalance",
    "inputs": [
      {
        "name": "sender",
        "type": "address"
      },
      {
        "name": "balance",
        "type": "uint256"
      },
      {
        "name": "needed",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC20InvalidApprover",
    "inputs": [
      {
        "name": "approver",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC20InvalidReceiver",
    "inputs": [
      {
        "name": "receiver",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC20InvalidSender",
    "inputs": [
      {
        "name": "sender",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC20InvalidSpender",
    "inputs": [
      {
        "name": "spender",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "Error",
    "inputs": [
      {
        "name": "message",
        "type": "string"
      }
    ]
  },
  {
    "type": "error",
    "name": "EscrowAlreadyExists",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "FailedDeployment",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FeeTooLow",
    "inputs": [
      {
        "name": "provided",
        "type": "uint256"
      },
      {
        "name": "minimum",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ImplementationAlreadyExists",
    "inputs": [
      {
        "name": "implementation",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ImplementationNotRegistered",
    "inputs": [
      {
        "name": "implementation",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InsufficientBalance",
    "inputs": [
      {
        "name": "balance",
        "type": "uint256"
      },
      {
        "name": "needed",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidContractAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidEvidence",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidExpiryTime",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidImplementationIndex",
    "inputs": [
      {
        "name": "index",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidInitialization",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidProposedExpiry",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidRuling",
    "inputs": [
      {
        "name": "ruling",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidState",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidTerms",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidToken",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoSeller",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotArbitrator",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAuthorizedDepositor",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotBuyer",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotCreator",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotFactory",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotInitializing",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotParty",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotSeller",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NothingToClaim",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Panic",
    "inputs": [
      {
        "name": "code",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "PendingOwnerOnly",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeCastOverflowedUintDowncast",
    "inputs": [
      {
        "name": "bits",
        "type": "uint8"
      },
      {
        "name": "value",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SameParty",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TooLate",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": []
  },
  {
    "type": "event",
    "name": "ArbitratorSet",
    "inputs": [
      {
        "name": "oldValue",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newValue",
        "type": "address",
        "indexed": true
      },
      {
        "name": "config",
        "type": "bytes",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BuyerApproved",
    "inputs": [
      {
        "name": "buyer",
        "type": "address",
        "indexed": true
      },
      {
        "name": "intent",
        "type": "uint8",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BuyerJoined",
    "inputs": [
      {
        "name": "buyer",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BuyerLeft",
    "inputs": [
      {
        "name": "buyer",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Cancelled",
    "inputs": [
      {
        "name": "cancelledBy",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DefaultEscrowImplementationSet",
    "inputs": [
      {
        "name": "oldDefault",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newDefault",
        "type": "address",
        "indexed": true
      },
      {
        "name": "name",
        "type": "string",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Dispute",
    "inputs": [
      {
        "name": "_arbitrator",
        "type": "address",
        "indexed": true
      },
      {
        "name": "_disputeId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "_metaEvidenceId",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "_evidenceGroupId",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DisputeRaised",
    "inputs": [
      {
        "name": "disputeId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "raisedBy",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EscrowCreated",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "creator",
        "type": "address",
        "indexed": true
      },
      {
        "name": "escrow",
        "type": "address",
        "indexed": true
      },
      {
        "name": "seller",
        "type": "address",
        "indexed": false
      },
      {
        "name": "buyer",
        "type": "address",
        "indexed": false
      },
      {
        "name": "token",
        "type": "address",
        "indexed": false
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "fee",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "expiryTime",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "settlementDeadline",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "termsHash",
        "type": "bytes32",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EscrowImplementationAdded",
    "inputs": [
      {
        "name": "implementation",
        "type": "address",
        "indexed": true
      },
      {
        "name": "name",
        "type": "string",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EscrowImplementationRemoved",
    "inputs": [
      {
        "name": "implementation",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Evidence",
    "inputs": [
      {
        "name": "_arbitrator",
        "type": "address",
        "indexed": true
      },
      {
        "name": "_evidenceGroupId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "_party",
        "type": "address",
        "indexed": true
      },
      {
        "name": "_evidence",
        "type": "string",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ExpiryExtended",
    "inputs": [
      {
        "name": "oldExpiry",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "newExpiry",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ExpiryExtensionConsented",
    "inputs": [
      {
        "name": "party",
        "type": "address",
        "indexed": true
      },
      {
        "name": "proposedExpiry",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FeeConfigSet",
    "inputs": [
      {
        "name": "oldRecipient",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newRecipient",
        "type": "address",
        "indexed": true
      },
      {
        "name": "oldBps",
        "type": "uint16",
        "indexed": false
      },
      {
        "name": "newBps",
        "type": "uint16",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Funded",
    "inputs": [
      {
        "name": "depositor",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "refundedExcess",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Initialized",
    "inputs": [
      {
        "name": "version",
        "type": "uint64",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MetaEvidence",
    "inputs": [
      {
        "name": "_metaEvidenceId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "_evidence",
        "type": "string",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MetaEvidenceURISet",
    "inputs": [
      {
        "name": "oldValue",
        "type": "string",
        "indexed": false
      },
      {
        "name": "newValue",
        "type": "string",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferInitiated",
    "inputs": [
      {
        "name": "currentOwner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "pendingOwner",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Refunded",
    "inputs": [
      {
        "name": "buyer",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Resolved",
    "inputs": [
      {
        "name": "seller",
        "type": "address",
        "indexed": true
      },
      {
        "name": "sellerPaid",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "buyer",
        "type": "address",
        "indexed": true
      },
      {
        "name": "buyerPaid",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "ruling",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Ruling",
    "inputs": [
      {
        "name": "_arbitrator",
        "type": "address",
        "indexed": true
      },
      {
        "name": "_disputeId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "_ruling",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SellerApproved",
    "inputs": [
      {
        "name": "seller",
        "type": "address",
        "indexed": true
      },
      {
        "name": "intent",
        "type": "uint8",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SellerJoined",
    "inputs": [
      {
        "name": "seller",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SellerLeft",
    "inputs": [
      {
        "name": "seller",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TermsHashUpdated",
    "inputs": [
      {
        "name": "updatedBy",
        "type": "address",
        "indexed": true
      },
      {
        "name": "oldTermsHash",
        "type": "bytes32",
        "indexed": false
      },
      {
        "name": "newTermsHash",
        "type": "bytes32",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "addEscrowImplementation",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "name",
        "type": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "aggregate3",
    "inputs": [
      {
        "name": "calls",
        "type": "tuple[]",
        "components": [
          {
            "name": "target",
            "type": "address"
          },
          {
            "name": "allowFailure",
            "type": "bool"
          },
          {
            "name": "callData",
            "type": "bytes"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "returnData",
        "type": "tuple[]",
        "components": [
          {
            "name": "success",
            "type": "bool"
          },
          {
            "name": "returnData",
            "type": "bytes"
          }
        ]
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "amount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "appeal",
    "inputs": [
      {
        "name": "_extraData",
        "type": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "appealCost",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "appealPeriod",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "approve",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "approve",
    "inputs": [
      {
        "name": "spender",
        "type": "address"
      },
      {
        "name": "value",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "arbitrationCost",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "arbitrator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "arbitratorConfiguration",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "buyer",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "buyerIntent",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cancel",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "claim",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createEscrow",
    "inputs": [
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "buyer",
            "type": "address"
          },
          {
            "name": "seller",
            "type": "address"
          },
          {
            "name": "token",
            "type": "address"
          },
          {
            "name": "amount",
            "type": "uint256"
          },
          {
            "name": "fee",
            "type": "uint256"
          },
          {
            "name": "expiryTime",
            "type": "uint256"
          },
          {
            "name": "settlementDeadline",
            "type": "uint256"
          },
          {
            "name": "termsHash",
            "type": "bytes32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createEscrow",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "buyer",
            "type": "address"
          },
          {
            "name": "seller",
            "type": "address"
          },
          {
            "name": "token",
            "type": "address"
          },
          {
            "name": "amount",
            "type": "uint256"
          },
          {
            "name": "fee",
            "type": "uint256"
          },
          {
            "name": "expiryTime",
            "type": "uint256"
          },
          {
            "name": "settlementDeadline",
            "type": "uint256"
          },
          {
            "name": "termsHash",
            "type": "bytes32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "creator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "defaultEscrowImplementation",
    "inputs": [],
    "outputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "name",
        "type": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deposit",
    "inputs": [],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "dispute",
    "inputs": [],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "disputeId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "escrowImplementationAt",
    "inputs": [
      {
        "name": "index",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "name",
        "type": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "escrowImplementationCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "extendExpiry",
    "inputs": [
      {
        "name": "newObligationDeadline",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "fee",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feeBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feeRecipient",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "initialize",
    "inputs": [
      {
        "name": "_creator",
        "type": "address"
      },
      {
        "name": "_buyer",
        "type": "address"
      },
      {
        "name": "_seller",
        "type": "address"
      },
      {
        "name": "_token",
        "type": "address"
      },
      {
        "name": "_amount",
        "type": "uint256"
      },
      {
        "name": "_fee",
        "type": "uint256"
      },
      {
        "name": "_fulfillmentDeadline",
        "type": "uint256"
      },
      {
        "name": "_settlementDeadline",
        "type": "uint256"
      },
      {
        "name": "_termsHash",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isCreateEscrowRequestValid",
    "inputs": [
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "buyer",
            "type": "address"
          },
          {
            "name": "seller",
            "type": "address"
          },
          {
            "name": "token",
            "type": "address"
          },
          {
            "name": "amount",
            "type": "uint256"
          },
          {
            "name": "fee",
            "type": "uint256"
          },
          {
            "name": "expiryTime",
            "type": "uint256"
          },
          {
            "name": "settlementDeadline",
            "type": "uint256"
          },
          {
            "name": "termsHash",
            "type": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isCreateEscrowRequestValid",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "buyer",
            "type": "address"
          },
          {
            "name": "seller",
            "type": "address"
          },
          {
            "name": "token",
            "type": "address"
          },
          {
            "name": "amount",
            "type": "uint256"
          },
          {
            "name": "fee",
            "type": "uint256"
          },
          {
            "name": "expiryTime",
            "type": "uint256"
          },
          {
            "name": "settlementDeadline",
            "type": "uint256"
          },
          {
            "name": "termsHash",
            "type": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "join",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "joinAsBuyer",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "joinAsSeller",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "leave",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "metaEvidenceURI",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "obligationDeadline",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingWithdrawals",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "predictEscrowAddress",
    "inputs": [
      {
        "name": "creator",
        "type": "address"
      },
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "buyer",
            "type": "address"
          },
          {
            "name": "seller",
            "type": "address"
          },
          {
            "name": "token",
            "type": "address"
          },
          {
            "name": "amount",
            "type": "uint256"
          },
          {
            "name": "fee",
            "type": "uint256"
          },
          {
            "name": "expiryTime",
            "type": "uint256"
          },
          {
            "name": "settlementDeadline",
            "type": "uint256"
          },
          {
            "name": "termsHash",
            "type": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "predictEscrowAddress",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "creator",
        "type": "address"
      },
      {
        "name": "req",
        "type": "tuple",
        "components": [
          {
            "name": "id",
            "type": "bytes32"
          },
          {
            "name": "buyer",
            "type": "address"
          },
          {
            "name": "seller",
            "type": "address"
          },
          {
            "name": "token",
            "type": "address"
          },
          {
            "name": "amount",
            "type": "uint256"
          },
          {
            "name": "fee",
            "type": "uint256"
          },
          {
            "name": "expiryTime",
            "type": "uint256"
          },
          {
            "name": "settlementDeadline",
            "type": "uint256"
          },
          {
            "name": "termsHash",
            "type": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "proposedObligationDeadline",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quoteGross",
    "inputs": [
      {
        "name": "net",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "gross",
        "type": "uint256"
      },
      {
        "name": "fee",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "refund",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "removeEscrowImplementation",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "removeParty",
    "inputs": [
      {
        "name": "party",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "rule",
    "inputs": [
      {
        "name": "_disputeId",
        "type": "uint256"
      },
      {
        "name": "_ruling",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "seller",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "sellerIntent",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setArbitrator",
    "inputs": [
      {
        "name": "newArb",
        "type": "address"
      },
      {
        "name": "newCfg",
        "type": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDefaultImplementation",
    "inputs": [
      {
        "name": "impl",
        "type": "address"
      },
      {
        "name": "name",
        "type": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setFeeConfig",
    "inputs": [
      {
        "name": "newRecipient",
        "type": "address"
      },
      {
        "name": "newBps",
        "type": "uint16"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMetaEvidenceURI",
    "inputs": [
      {
        "name": "newURI",
        "type": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settlementDeadline",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "state",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "submitEvidence",
    "inputs": [
      {
        "name": "_evidence",
        "type": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "sweep",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "termsHash",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "token",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "updateTermsHash",
    "inputs": [
      {
        "name": "_termsHash",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  }
] as const;

export const EVENT_TOPICS = {
  "EscrowCreated": "0x429039ffd894c9f595ef32aeb37088bafbe6430f132e2f117e0eec5e6e5a2dc0",
  "Funded": "0xcd909ec339185c4598a4096e174308fbdf136d117f230960f873a2f2e81f63af",
  "Resolved": "0xb31e04c54dd6819aa0d524f72be0077f5d23d35a14bd77a500077297271dffd6",
  "DisputeRaised": "0x84a477df8a28a4276ca6dee4458a06c3015f30c477d9c949ede4e13ff8a552b4",
  "Cancelled": "0x398bd6b21ae4164ec322fb0eb8c2eb6277f36fd41903fbbed594dfe125591281",
  "BuyerApproved": "0xb6f576453eed8d2d263947bb7e38db5ec701913973bbb3f221fba761a5f6ca39",
  "SellerApproved": "0xa71f10ab21320099dbf18c57ef73316dd28bf008994812fca2ba9273fcdfb668",
  "ExpiryExtended": "0xd9a191afe85bc2031508928e3adc9a8eae20f43c8186ecc387f5e1397f5512ea",
  "TermsHashUpdated": "0xe068583800881d4946653d2df8561fdee8ef5880e87ff935a99cf924aeb1bc94",
  "Evidence": "0xdccf2f8b2cc26eafcd61905cba744cff4b81d14740725f6376390dc6298a6a3c",
  "BuyerJoined": "0x905e777bec48d02a92d6c589a2d950fd0b72402db8de95d97ec9c61e9a1c42b6",
  "BuyerLeft": "0xeb1abed92c4e5896089357a79f75532af5067ed0ecc6dcf605f34bd7c3a0e1f4",
  "SellerJoined": "0x5ba6a3ab6c58076d58e28977cf2ce7206c32d55fc3a6cacb10eb32c0857ba937",
  "SellerLeft": "0x834cb3d76739f52cfe903fd265d494cca0c1286720ffebbc1c20dfc76c9abaea",
  "ExpiryExtensionConsented": "0xb3469a6b033f0f91a46c6270131edc8552abf59417b18274046de6b96c9e6885"
} as const;
